/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingdemo;
import java.sql.*;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import static swingdemo.swingdb.sdb;

/**
 *
 * @author MJ
 */
public class swingdem extends javax.swing.JFrame{

    /**
     * Creates new form swing demo 
     */
    public swingdem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtmname = new javax.swing.JLabel();
        txtlname = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        txtadd = new javax.swing.JLabel();
        txtflname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtfemailid = new javax.swing.JTextField();
        txtfmno = new javax.swing.JTextField();
        txtfmname = new javax.swing.JTextField();
        txtmno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        txtgender = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        txtgender1 = new javax.swing.JLabel();
        submitb = new javax.swing.JButton();
        resetb = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 153, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("User Registration Form");

        txtname.setText("Name");

        txtmname.setText("Middle Name");

        txtlname.setText("Last Name");

        txtemail.setText("Email Id ");

        txtadd.setText("Address");

        txtflname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflnameActionPerformed(evt);
            }
        });
        txtflname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtflnameKeyTyped(evt);
            }
        });

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });

        txtfmno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfmnoActionPerformed(evt);
            }
        });
        txtfmno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfmnoKeyTyped(evt);
            }
        });

        txtfmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfmnameActionPerformed(evt);
            }
        });
        txtfmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfmnameKeyTyped(evt);
            }
        });

        txtmno.setText("Mobile No ");

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        buttonGroup1.add(rb1);
        rb1.setText("Male");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        rb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb1KeyPressed(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setText("Other");

        buttonGroup1.add(rb2);
        rb2.setText("Female");
        rb2.setToolTipText("");

        txtgender.setText("Gender ");

        buttonGroup2.add(jToggleButton1);
        jToggleButton1.setText("Yes");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jToggleButton2);
        jToggleButton2.setText("No");

        txtgender1.setText("Education Gap");

        submitb.setText("Submit");
        buttonGroup3.add(submitb);
        submitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbActionPerformed(evt);
            }
        });

        resetb.setText("Reset");
        buttonGroup3.add(resetb);
        resetb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetbMouseClicked(evt);
            }
        });
        resetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Middle Name", "Last Name", "Email Id", "Mobile No", "Address", "Gender"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(372, 372, 372))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtadd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb2)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtflname)
                                        .addComponent(txtfemailid, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addComponent(txtfmno, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addComponent(txtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addComponent(txtfmname, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtgender1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(submitb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(resetb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtflname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfmno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtadd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(txtgender1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitb)
                    .addComponent(resetb))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtfmnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfmnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfmnoActionPerformed

    private void txtflnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtflnameActionPerformed

    private void txtfmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfmnameActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void submitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbActionPerformed
        // TODO add your handling code here:
        String name = txtfname.getText();
        String lname = txtflname.getText();
        String mname = txtfmname.getText();
        String email = txtfemailid.getText();
        String mobile = txtfmno.getText();
        String add = txtaddress.getText();
        String male = rb1.getName();
        String female = rb2.getName();
        String other = rb3.getName();
        
        if(name.isEmpty())
        {
            System.out.println("Name Cannot be Empty : "+name);
        }
        else{
            System.out.println("Name is :"+name);
        }
         if(mname.isEmpty())
        {
            System.out.println("Middle Name Cannot be Empty : "+mname);
        }else{
              System.out.println("Middle Name is :"+mname);
         }
        if(lname.isEmpty())
        {
            System.out.println("Last Name Cannot be Empty Last Name: "+lname);
        }
        else{
             System.out.println("Last Name is :"+lname);
        }
        if(email.isEmpty())
        {
            System.out.println("Email id Cannot be Empty : "+email);
        }
        else
        {
            System.out.println("Emailid is :"+email);
        }
         if(mobile.isEmpty())
        {
            System.out.println("Mobile No Cannot be Empty : "+mobile);
          
        }
         if(mobile.length()>10)
            {
                System.out.println("Number Is Incorrect:");
            }else{
             System.out.println("Mobile number is :"+mobile);
         }
         
          if(add.isEmpty())
        {
            System.out.println("Address field Cannot be Empty: "+add);
        }else{
                System.out.println("Address is :"+add);
          }
          
          String a="";
          if(rb1.isSelected())
          { a="male";
              System.out.println("Gender :"+a);
          }
          else if(rb2.isSelected()){
              a="female";
              System.out.println("Gender :"+a);
          }else{
              a="other";
              System.out.println("Gender :"+a);
              
          }
            try{
                 Connection db = sdb();
                 Statement st = db.createStatement();
                 String query;
                query = "insert into swing values('"+name+"','"+mname+"','"+lname+"','"+email+"','"+mobile+"','"+add+"','"+a+"')";
                st.executeUpdate(query);

            
                }
            catch(Exception e)
                {
                        System.out.println(e);
                }
          
            Vector <String> v = new Vector<>();
            DefaultTableModel dml = (DefaultTableModel) jTable1.getModel();
            v.add(name);    //when we are connecting database then will take input 
                            // like v.add(rs.getString(1);
            v.add(mname);
            v.add(lname);
            v.add(email);
            v.add(mobile);
            v.add(add);
            v.add(a);
           dml.addRow(v); 
    }//GEN-LAST:event_submitbActionPerformed

    private void resetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbActionPerformed
        // TODO add your handling code here:
//        request.setStatus(request.SC_SEE_OTHER);
//            txtfname.setText("");
            clearFields();
    }//GEN-LAST:event_resetbActionPerformed

    private void txtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtfnameKeyPressed

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_B ) || (c==KeyEvent.VK_DELETE)))
           evt.consume();
       
    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtfmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfmnameKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_B ) || (c==KeyEvent.VK_DELETE)))
           evt.consume();
     
    }//GEN-LAST:event_txtfmnameKeyTyped

    private void txtflnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtflnameKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_B ) || (c==KeyEvent.VK_DELETE)))
           evt.consume();
    }//GEN-LAST:event_txtflnameKeyTyped

    private void txtfmnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfmnoKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || (c==KeyEvent.VK_B ) || (c==KeyEvent.VK_DELETE)))
           evt.consume();
    }//GEN-LAST:event_txtfmnoKeyTyped

    private void resetbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbMouseClicked
   
          
    }//GEN-LAST:event_resetbMouseClicked

    private void rb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb1KeyPressed

    }//GEN-LAST:event_rb1KeyPressed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
        String name = txtfname.getText();
        String lname = txtflname.getText();
        String mname = txtfmname.getText();
        String email = txtfemailid.getText();
        String mobile = txtfmno.getText();
        String add = txtaddress.getText();
        String male = rb1.getName();
        String female = rb2.getName();
        String other = rb3.getName();
    }//GEN-LAST:event_jTable1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(swingdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(swingdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(swingdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(swingdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new swingdem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JButton resetb;
    private javax.swing.JButton submitb;
    private javax.swing.JLabel txtadd;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JLabel txtemail;
    private javax.swing.JTextField txtfemailid;
    private javax.swing.JTextField txtflname;
    private javax.swing.JTextField txtfmname;
    private javax.swing.JTextField txtfmno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JLabel txtgender;
    private javax.swing.JLabel txtgender1;
    private javax.swing.JLabel txtlname;
    private javax.swing.JLabel txtmname;
    private javax.swing.JLabel txtmno;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables

    private void clearFields(){
        txtfname.setText(null);
        txtflname.setText(null);
        txtfmname.setText(null);
        txtfemailid.setText(null);
        txtfmno.setText(null);
        txtaddress.setText(null);
        }
}
