/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationtask;

import com.sun.glass.events.KeyEvent;
import static java.lang.Class.forName;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static registrationtask.maindb.regist;


/**
 *
 * @author MJ
 */
public class Signuppage extends javax.swing.JFrame {

    /**
     * Creates new form Sign-up page
     */
    public Signuppage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        lsname = new javax.swing.JLabel();
        lrpassword = new javax.swing.JLabel();
        lgender = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tsname = new javax.swing.JTextField();
        tpassword = new javax.swing.JPasswordField();
        trpassword = new javax.swing.JPasswordField();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        bsubmit = new javax.swing.JButton();
        bclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("                                                                SIGN UP PAGE ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        lemail.setText("EMAIL ID");
        lemail.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        lname.setText("NAME");
        lname.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        lpassword.setText("PASSWORD");
        lpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        lsname.setText("SURNAME");
        lsname.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        lrpassword.setText("RE TYPE PASSWORD");
        lrpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        lgender.setText("Gender ");
        lgender.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));

        tname.setBackground(new java.awt.Color(255, 51, 51));
        tname.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnameKeyTyped(evt);
            }
        });

        temail.setBackground(new java.awt.Color(255, 51, 51));
        temail.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temailKeyTyped(evt);
            }
        });

        tsname.setBackground(new java.awt.Color(255, 51, 51));
        tsname.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        tsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsnameActionPerformed(evt);
            }
        });
        tsname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tsnameKeyTyped(evt);
            }
        });

        tpassword.setBackground(new java.awt.Color(255, 51, 51));
        tpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });

        trpassword.setBackground(new java.awt.Color(255, 51, 51));
        trpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        trpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trpasswordActionPerformed(evt);
            }
        });

        rb2.setBackground(new java.awt.Color(255, 51, 51));
        buttonGroup1.add(rb2);
        rb2.setText("Female");
        rb2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.yellow));
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb1.setBackground(new java.awt.Color(255, 51, 51));
        buttonGroup1.add(rb1);
        rb1.setText("Male");
        rb1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.yellow));

        bsubmit.setBackground(new java.awt.Color(255, 51, 51));
        bsubmit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bsubmit.setText("SUBMIT");
        bsubmit.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        buttonGroup2.add(bsubmit);
        bsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsubmitMouseClicked(evt);
            }
        });
        bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubmitActionPerformed(evt);
            }
        });

        bclear.setBackground(new java.awt.Color(255, 51, 51));
        bclear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bclear.setText("CLEAR");
        bclear.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        buttonGroup2.add(bclear);
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lgender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lrpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(lpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lsname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tname)
                                    .addComponent(temail, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                                    .addComponent(tsname, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                                    .addComponent(tpassword)
                                    .addComponent(trpassword)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(bsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tname)
                    .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tsname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lrpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsnameActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void trpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trpasswordActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void bsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubmitActionPerformed
                // TODO add your handling code here:
        try{ 
            Connection db = regist();
                Statement st = db.createStatement();
                String query;            
            
            
            int flag = 0;
            
                String name = tname.getText();
                String sname = tsname.getText();
                String email = temail.getText();
                String password =tpassword.getText();
                String repassword = trpassword.getText();
                String male = rb1.getName();
                String female = rb2.getName();
                
                 String a = " ";
               if(rb1.isSelected())
               {
                   a = "Male";
               }else{
                   a = "female";
               }
                
           /*      if(name == null || address == null || phoneNumber == null || dob == null 
                || password == null || password2 == null)
            {
                //Error message appears to prompt the user to 
                //complete the form
                JOptionPane.showMessageDialog(null, "All fields must be complete to submit.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            */ 
               String emailf="^[A-Za-z0-9+_.-]+@(.+)$";
               Pattern pt = Pattern.compile(emailf);
                if(name.isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "name field Cannot be Empty :");
                    flag=1;
                }
                else if(sname.isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "sname field Cannot be Empty :");
                    flag=1;
                }
                else if(email.isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "email field Cannot be Empty :");
                    flag=1;
                }else if(!pt.matcher(email).matches())
                {
                    JOptionPane.showMessageDialog(rootPane,"In valid Email:" ,"Oops", JOptionPane.ERROR_MESSAGE);
                    flag=1;
                }
                else if(password.isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "password field Cannot be Empty :");
                    flag=1;
                }
                else if(repassword.isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "repassword field Cannot be Empty :");
                    flag=1;
                }
                else if(password.length()!= repassword.length()){
                    JOptionPane.showMessageDialog(rootPane, "Password Length dosen't match","Oops", JOptionPane.ERROR_MESSAGE);
                   flag = 1;
                }//else if (password != repassword )
                else if((!Arrays.equals(tpassword.getPassword(), trpassword.getPassword())))
                {
                     JOptionPane.showMessageDialog(null, "Passwords do not match."," Oops",  JOptionPane.ERROR_MESSAGE);
                    tpassword.setText(null);
                    trpassword.setText(null);
                    flag = 1;
                }
                else if(password.equals(repassword))
                {
                    System.out.println("All Field are Proper...:");
                     mainpage mp = new mainpage();
                        mp.show();
                        this.hide();
                    flag=0;                      
                }
                 if(flag==0)
                {   query ="insert into signup values('"+name+"','"+sname+"','"+email+"','"+password+"','"+repassword+"','"+a+"')";
                    st.executeUpdate(query);
                  
                    System.out.println("Data is Added in Table:");
                    
                }
        } 
        catch(Exception e)
            {
                System.out.println(e);
            }
                
                    
    
        
//        Signuppage sp=new Signuppage();
//        sp.show();
//        this.hide();

            

           
    }//GEN-LAST:event_bsubmitActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        clearfield();
    }//GEN-LAST:event_bclearActionPerformed

    private void bsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bsubmitMouseClicked

    private void tnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyTyped
        // TODO add your handling code here:
      char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c == KeyEvent.VK_B) || (c == KeyEvent.VK_DELETE) ))
            evt.consume();
    }//GEN-LAST:event_tnameKeyTyped

    private void tsnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c == KeyEvent.VK_B) || (c == KeyEvent.VK_DELETE) ))
            evt.consume();
    }//GEN-LAST:event_tsnameKeyTyped

    private void temailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDefined(c)|| (c == KeyEvent.VK_B) || (c == KeyEvent.VK_DELETE) ))
            evt.consume();
    }//GEN-LAST:event_temailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signuppage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclear;
    private javax.swing.JButton bsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lgender;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lrpassword;
    private javax.swing.JLabel lsname;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JPasswordField trpassword;
    private javax.swing.JTextField tsname;
    // End of variables declaration//GEN-END:variables

    private void clearfield()
    {
        tname.setText(null);
        tsname.setText(null);
        temail.setText(null);
        tpassword.setText(null);
        trpassword.setText(null);
        
    }
   
}
